language: go
sudo: false
go:
- 1.8
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
os:
- linux
script:
- go build -race
- go test -v ./...
- go vet
- cd test; go run test.go $LOGZ
env:
  global:
  - secure: hu/7RZMNjb6n/xMYZpyIU5x3usizMCOJeQjGI9PWuOZDVSUaCyQZIjN11IHWqu0MBdbfI8aXZtF1JUXMgZ85dd6NsZ3RQIVMqFs7CQr/Dawvd6Bb1Fu2xQ3sJ882LXxmRV+DnxwFCenCW3e0V0KCzG8dNedgmNn16Tau32so5H7zTYlxjcPIckN/CHMqe6C3FGf6HyANe9r9NYmooPkfoB0Gsa4ncf5x8oWwDRgcouPJummQv6sl64CEAJlNiUmp3SXbcG6a094wy1I3yuelpmHnpEog+cFvF9mk6WTeetmMnfoZRtQ7mGcq7AhEHXj2sBqScCiClP1dibX9rwk5n9Rt9lsbAv8SJyB6c3br5jdYTFeEs6vDCjiJPXoY1fe7TC0wBNjSUNKgXzmTliFWnSVWNDgDewm2HuoGPNQO3DDDHNeKIs29eLUS8V8nhQgJeRaTQK+RjrH49NiDjE4Z2E9+PgXUqRxH0pGjsUsT/WtOyKTwamUzb1PKsw3FPQsI2lPrNoxjVmw4Fl/7FR9lyqSpIVPmOYqjdSdjN1ACtVnPmwSf2xX7LcgqVbLqISi/lVsQd3hEgsXPZ4/bbeVF4MpZKbJ4UKtyRy1wwq9LuAonW5ayRPy3k6K7qCrGSpMNGsHelabCKd9WN8EAuQ2ndCyWXS9kUQxxjuwGKXd+ms0=
