language: go
sudo: false
go:
- 1.9.2
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
os:
- linux
script:
- go build -race
- go test -v ./...
- cd test; go run test.go $LOGZ
env:
  global:
    secure: lyrrNZd5JG8u1YCHoo695LoE0e1pvr5AQOIfUvwrnnfMd0qBd5iaVtgtafw4oCpzPSX0gDzvQ2hYtay28HfqB7S+R3VimGHlngk8xOrGguSB+R9UWVamy0CLhRlz7g6p9iBwgUCXyxE2Wlbje/7TPyfH4VGAlZl+tcOhdfUc6SIsWzw9yB+qMfufE9hro2pU2d7O6sSE+uY4yjTqQLwT8uv0VSlPtJ6Juzxbul+xu9NGlESePtwCC+Y+0R+tLefVk1htoOm+dewYr546D2O7KYUryVmVxuNm0irch5PbcnWrFcTUCtahIKUUByehjY3/cJWhzcPC8S9IRV0V+z7/PRS33N44jTHelEao2M/BFLmWTbLQJpJrNpdnvvbEE17503f89Dt41bv/dxbgct4rrnBKjB7W9MkT+vyo1gHppGdYGZLyQ2XeX7Va/ZogrHwfIRM6+jQ/rueoBbgwf1OXyb8BvhIJa/+DLoDlJuvFWhBuxN6nWZsWKAMZWZHCZfR1dPCP3USQxPEApNFqlmwBdt2sXcdy/I8o+Z4VRotnwjKs8kNy1KW1LsHc7pgZ2XQyk/p38xAoHJU4rocumy0QDCg1S0fW63bDWaXP46JNHXCV7zk4KRufJE6uu0C4s4t63kU8qR4wEjSselhaXenC9cAT4GzzgzDiShtFIacpJGk=
